import styles from "./PanelHash.module.scss"
import { useContext } from "react"
import { MainContext } from "context/MainContext"

import RefreshIcon from "../../assets/rotate-right-solid.svg"
import { PanelGroup } from "components/Panel/PanelGroup"
import { BaseInput, IconButton } from "components/FxParams/BaseInput"
const getNewHash = () => {
  let alphabet = "123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"
  return (
    "oo" +
    Array(49)
      .fill(0)
      .map((_) => alphabet[(Math.random() * alphabet.length) | 0])
      .join("")
  )
}

interface Props {}
export function PanelHash({}: Props) {
  const ctx = useContext(MainContext)

  const handleChange = (e: any) => {
    ctx.setHash(e.target.value)
  }
  const handleRefresh = () => {
    ctx.setHash(getNewHash())
  }

  return (
    <PanelGroup
      title="Current seed"
      description="The seed is generated by the signing module. Here you can test
      different seeds with your params."
    >
      <div className={styles.hashControls}>
        <BaseInput type="text" value={ctx.hash} onChange={handleChange} className={styles.hashInput} />
        <IconButton onClick={handleRefresh}>
          <img src={RefreshIcon} />
        </IconButton>
      </div>
    </PanelGroup>
  )
}
