import styles from "./PanelHash.module.scss"
import { useContext } from "react"
import { PanelGroup } from "components/Panel/PanelGroup"
import { BaseInput, IconButton } from "components/FxParams/BaseInput"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { RuntimeContext } from "context/RuntimeContext"
import { IconTezos } from "components/Icon/Tezos"
import { faEthereum } from "@fortawesome/free-brands-svg-icons"
import { mockTransactionHash } from "@fxhash/utils"

export function PanelHash() {
  const runtime = useContext(RuntimeContext)

  const handleChange = (e: any) => {
    runtime.state.update({ hash: e.target.value })
  }
  const handleRefresh = (hash: string) => {
    runtime.state.update({ hash })
  }

  return (
    <PanelGroup
      title="Current seed"
      description="The seed is generated by the signing module. Here you can test
      different seeds with your params."
    >
      <div className={styles.hashControls}>
        <BaseInput
          type="text"
          value={runtime.state.hash}
          onChange={handleChange}
          className={styles.hashInput}
        />
        <IconButton
          onClick={() => handleRefresh(mockTransactionHash("TEZOS"))}
          color="secondary"
        >
          <IconTezos />
        </IconButton>
        <IconButton
          onClick={() => handleRefresh(mockTransactionHash("ETHEREUM"))}
          color="secondary"
        >
          <FontAwesomeIcon icon={faEthereum} size="1x" />
        </IconButton>
      </div>
    </PanelGroup>
  )
}
