import styles from "./PanelHash.module.scss"
import { useContext } from "react"
import { MainContext } from "context/MainContext"
import { faRotate } from "@fortawesome/free-solid-svg-icons"
import { PanelGroup } from "components/Panel/PanelGroup"
import { BaseInput, IconButton } from "components/FxParams/BaseInput"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { RuntimeContext } from "context/RuntimeContext"

const getNewHash = () => {
  const alphabet = "123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"
  return (
    "oo" +
    Array(49)
      .fill(0)
      .map((_) => alphabet[(Math.random() * alphabet.length) | 0])
      .join("")
  )
}

export function PanelHash() {
  const ctx = useContext(MainContext)
  const runtime = useContext(RuntimeContext)

  const handleChange = (e: any) => {
    runtime.state.update({ hash: e.target.value })
  }
  const handleRefresh = () => {
    runtime.state.update({ hash: getNewHash() })
  }

  return (
    <PanelGroup
      title="Current seed"
      description="The seed is generated by the signing module. Here you can test
      different seeds with your params."
    >
      <div className={styles.hashControls}>
        <BaseInput
          type="text"
          value={runtime.state.hash}
          onChange={handleChange}
          className={styles.hashInput}
        />
        <IconButton onClick={handleRefresh} color="secondary">
          <FontAwesomeIcon icon={faRotate} size="1x" />
        </IconButton>
      </div>
    </PanelGroup>
  )
}
